chore: update installer.sh with innovations from rustup.sh
This script is descended from rustup.sh, and they have way more people cleaning it up,
so let's snag the improvements.

* add shellcheck annotation (and fix issues)
* update platform detection
* properly handle variable detection with `set -u`

diff --git a/cargo-dist/templates/installer.sh.j2 b/cargo-dist/templates/installer.sh.j2
--- a/cargo-dist/templates/installer.sh.j2
+++ b/cargo-dist/templates/installer.sh.j2
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/bin/sh
+# shellcheck shell=dash
 #
 # Licensed under the MIT license
 # <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
@@ -7,15 +8,21 @@
 
 # This is just a little script that can be downloaded from the internet to
 # install $APP_NAME. It downloads the tarball from ARTIFACT_DOWNLOAD_URL,
-# and extracts it to ~/.cargo/bin/
+# and extracts it to an appropriate directory.
 #
 # In the future this script will gain extra features, but for now it's
 # intentionally very simplistic to avoid shipping broken things.
 
+if [ "$KSH_VERSION" = 'Version JM 93t+ 2010-03-05' ]; then
+    # The version of ksh93 that ships with many illumos systems does not
+    # support the "local" extension.  Print a message rather than fail in
+    # subtle ways later on:
+    echo 'this installer does not work with this ksh93 version; please try bash!' >&2
+    exit 1
+fi
+
 set -u
 
-# FIXME: patch in the repo's URL for suggesting filling an issue
-# REPO="{{REPO_URL}}"
 APP_NAME="{{ app_name }}"
 APP_VERSION="{{ app_version }}"
 ARTIFACT_DOWNLOAD_URL="{{ base_url }}"
@@ -38,25 +45,30 @@ download_binary_and_run_installer() {
     local _arch="$RETVAL"
     assert_nz "$_arch" "arch"
 
-    local _bins=""
-    local _zip_ext=""
-    local _artifact_name=""
+    local _bins
+    local _zip_ext
+    local _artifact_name
 
-    # This """lookup table""" is generated by cargo-dist
-    # and populates the above locals with the right values
+    # Lookup what to download/unpack based on platform
     case "$_arch" in {% for artifact in artifacts %}
         "{{ artifact.target_triples[0] }}")
             _artifact_name="{{ artifact.id }}"
             _zip_ext="{{ artifact.zip_style }}"
-            _bins="{% for bin in artifact.binaries %}{{ bin }}{{ " " if not loop.last else "" }}{% endfor %}"{% endfor %}
+            _bins="{% for bin in artifact.binaries %}{{ bin }}{{ " " if not loop.last else "" }}{% endfor %}"
+            ;;{% endfor %}
         *)
             err "there isn't a package for $_arch"
             ;;
     esac
 
-    # download the zip
+    # download the archive
     local _url="$ARTIFACT_DOWNLOAD_URL/$_artifact_name"
-    local _dir="$(mktemp -d 2>/dev/null || ensure mktemp -d -t $APP_NAME)"
+    local _dir
+    if ! _dir="$(ensure mktemp -d)"; then
+        # Because the previous command ran in a subshell, we must manually
+        # propagate exit status.
+        exit 1
+    fi
     local _file="$_dir/input$_zip_ext"
 
     say "downloading $APP_NAME $APP_VERSION ${_arch}" 1>&2
@@ -64,8 +76,8 @@ download_binary_and_run_installer() {
     say "  to $_file" 1>&2
 
     ensure mkdir -p "$_dir"
-    downloader "$_url" "$_file"
-    if [ $? != 0 ]; then
+    
+    if ! downloader "$_url" "$_file"; then
       say "failed to download $_url"
       say "this may be a standard network error, but it may also indicate"
       say "that $APP_NAME's release process is not working. When in doubt"
@@ -102,26 +114,26 @@ download_binary_and_run_installer() {
 }
 
 install() {
-    local _install_dir=""
+    local _install_dir
 {% if install_path.kind == "CargoHome" %}
     # first try CARGO_HOME, then fallback to HOME
-    if [[ -z $CARGO_HOME ]]; then
+    if [ -n "${CARGO_HOME:-}" ]; then
         _install_dir="$CARGO_HOME/bin/"
-    elif [[ -z $HOME ]]; then
+    elif [ -n "${HOME:-}" ]; then
         _install_dir="$HOME/.cargo/bin/"
     else
         err "could not find your CARGO_HOME or HOME dir to install binaries to"
     fi
 {% elif install_path.kind == "HomeSubdir" %}
     # Install to this subdir of the user's home dir
-    if [[ -z $HOME ]]; then
+    if [ -n "${HOME:-}" ]; then
         _install_dir="$HOME/{{ install_path.subdir }}"
     else
         err "could not find your HOME dir to install binaries to"
     fi
 {% elif install_path.kind == "EnvSubdir" %}
     # Install to this subdir of the user's {{ install_path.env_key }} dir
-    if [[ -z ${{ install_path.env_key }} ]]; then
+    if [ -n "{{ "${" }}{{ install_path.env_key }}:-}" ]; then
         _install_dir="${{ install_path.env_key }}/{{ install_path.subdir }}"
     else
         err "could not find your {{ install_path.env_key }} dir to install binaries to"
@@ -145,95 +157,279 @@ install() {
     say "everything's installed!"
 }
 
-get_architecture() {
-    local _ostype="$(uname -s)"
-    local _cputype="$(uname -m)"
+check_proc() {
+    # Check for /proc by looking for the /proc/self/exe link
+    # This is only run on Linux
+    if ! test -L /proc/self/exe ; then
+        err "fatal: Unable to find /proc/self/exe.  Is /proc mounted?  Installation cannot proceed without /proc."
+    fi
+}
 
-    if [ "$_ostype" = Darwin -a "$_cputype" = i386 ]; then
-        # Darwin `uname -s` lies
-        if sysctl hw.optional.x86_64 | grep -q ': 1'; then
-            local _cputype=x86_64
+get_bitness() {
+    need_cmd head
+    # Architecture detection without dependencies beyond coreutils.
+    # ELF files start out "\x7fELF", and the following byte is
+    #   0x01 for 32-bit and
+    #   0x02 for 64-bit.
+    # The printf builtin on some shells like dash only supports octal
+    # escape sequences, so we use those.
+    local _current_exe_head
+    _current_exe_head=$(head -c 5 /proc/self/exe )
+    if [ "$_current_exe_head" = "$(printf '\177ELF\001')" ]; then
+        echo 32
+    elif [ "$_current_exe_head" = "$(printf '\177ELF\002')" ]; then
+        echo 64
+    else
+        err "unknown platform bitness"
+    fi
+}
+
+is_host_amd64_elf() {
+    need_cmd head
+    need_cmd tail
+    # ELF e_machine detection without dependencies beyond coreutils.
+    # Two-byte field at offset 0x12 indicates the CPU,
+    # but we're interested in it being 0x3E to indicate amd64, or not that.
+    local _current_exe_machine
+    _current_exe_machine=$(head -c 19 /proc/self/exe | tail -c 1)
+    [ "$_current_exe_machine" = "$(printf '\076')" ]
+}
+
+get_endianness() {
+    local cputype=$1
+    local suffix_eb=$2
+    local suffix_el=$3
+
+    # detect endianness without od/hexdump, like get_bitness() does.
+    need_cmd head
+    need_cmd tail
+
+    local _current_exe_endianness
+    _current_exe_endianness="$(head -c 6 /proc/self/exe | tail -c 1)"
+    if [ "$_current_exe_endianness" = "$(printf '\001')" ]; then
+        echo "${cputype}${suffix_el}"
+    elif [ "$_current_exe_endianness" = "$(printf '\002')" ]; then
+        echo "${cputype}${suffix_eb}"
+    else
+        err "unknown platform endianness"
+    fi
+}
+
+get_architecture() {
+    local _ostype
+    local _cputype
+    _ostype="$(uname -s)"
+    _cputype="$(uname -m)"
+    local _clibtype="gnu"
+
+    if [ "$_ostype" = Linux ]; then
+        if [ "$(uname -o)" = Android ]; then
+            _ostype=Android
+        fi
+        if ldd --version 2>&1 | grep -q 'musl'; then
+            _clibtype="musl"
         fi
     fi
 
-    if [ "$_ostype" = Darwin -a "$_cputype" = arm64 ]; then
-        # Darwin `uname -s` doesn't seem to lie on Big Sur
-        # but the cputype we want is called aarch64, not arm64 (they are equivalent)
-        local _cputype=aarch64
+    if [ "$_ostype" = Darwin ] && [ "$_cputype" = i386 ]; then
+        # Darwin `uname -m` lies
+        if sysctl hw.optional.x86_64 | grep -q ': 1'; then
+            _cputype=x86_64
+        fi
+    fi
+
+    if [ "$_ostype" = SunOS ]; then
+        # Both Solaris and illumos presently announce as "SunOS" in "uname -s"
+        # so use "uname -o" to disambiguate.  We use the full path to the
+        # system uname in case the user has coreutils uname first in PATH,
+        # which has historically sometimes printed the wrong value here.
+        if [ "$(/usr/bin/uname -o)" = illumos ]; then
+            _ostype=illumos
+        fi
+
+        # illumos systems have multi-arch userlands, and "uname -m" reports the
+        # machine hardware name; e.g., "i86pc" on both 32- and 64-bit x86
+        # systems.  Check for the native (widest) instruction set on the
+        # running kernel:
+        if [ "$_cputype" = i86pc ]; then
+            _cputype="$(isainfo -n)"
+        fi
     fi
 
     case "$_ostype" in
+
+        Android)
+            _ostype=linux-android
+            ;;
+
         Linux)
-            if has_required_glibc; then
-                local _ostype=unknown-linux-gnu
-            else
-                local _ostype=unknown-linux-musl
-                say "Downloading musl binary."
-            fi
+            check_proc
+            _ostype=unknown-linux-$_clibtype
+            _bitness=$(get_bitness)
+            ;;
+
+        FreeBSD)
+            _ostype=unknown-freebsd
+            ;;
+
+        NetBSD)
+            _ostype=unknown-netbsd
+            ;;
+
+        DragonFly)
+            _ostype=unknown-dragonfly
             ;;
 
         Darwin)
-            local _ostype=apple-darwin
+            _ostype=apple-darwin
             ;;
 
-        MINGW* | MSYS* | CYGWIN*)
-            local _ostype=pc-windows-msvc
+        illumos)
+            _ostype=unknown-illumos
+            ;;
+
+        MINGW* | MSYS* | CYGWIN* | Windows_NT)
+            _ostype=pc-windows-gnu
             ;;
 
         *)
-            err "no precompiled binaries available for OS: $_ostype"
+            err "unrecognized OS type: $_ostype"
             ;;
+
     esac
 
     case "$_cputype" in
-        # these are the only two acceptable values for cputype
-        x86_64 | aarch64 )
+
+        i386 | i486 | i686 | i786 | x86)
+            _cputype=i686
+            ;;
+
+        xscale | arm)
+            _cputype=arm
+            if [ "$_ostype" = "linux-android" ]; then
+                _ostype=linux-androideabi
+            fi
+            ;;
+
+        armv6l)
+            _cputype=arm
+            if [ "$_ostype" = "linux-android" ]; then
+                _ostype=linux-androideabi
+            else
+                _ostype="${_ostype}eabihf"
+            fi
+            ;;
+
+        armv7l | armv8l)
+            _cputype=armv7
+            if [ "$_ostype" = "linux-android" ]; then
+                _ostype=linux-androideabi
+            else
+                _ostype="${_ostype}eabihf"
+            fi
+            ;;
+
+        aarch64 | arm64)
+            _cputype=aarch64
+            ;;
+
+        x86_64 | x86-64 | x64 | amd64)
+            _cputype=x86_64
+            ;;
+
+        mips)
+            _cputype=$(get_endianness mips '' el)
+            ;;
+
+        mips64)
+            if [ "$_bitness" -eq 64 ]; then
+                # only n64 ABI is supported for now
+                _ostype="${_ostype}abi64"
+                _cputype=$(get_endianness mips64 '' el)
+            fi
+            ;;
+
+        ppc)
+            _cputype=powerpc
+            ;;
+
+        ppc64)
+            _cputype=powerpc64
+            ;;
+
+        ppc64le)
+            _cputype=powerpc64le
+            ;;
+
+        s390x)
+            _cputype=s390x
+            ;;
+        riscv64)
+            _cputype=riscv64gc
+            ;;
+        loongarch64)
+            _cputype=loongarch64
             ;;
         *)
-            err "no precompiled binaries available for CPU architecture: $_cputype"
+            err "unknown CPU type: $_cputype"
 
     esac
 
-    local _arch="$_cputype-$_ostype"
+    # Detect 64-bit linux with 32-bit userland
+    if [ "${_ostype}" = unknown-linux-gnu ] && [ "${_bitness}" -eq 32 ]; then
+        case $_cputype in
+            x86_64)
+                # 32-bit executable for amd64 = x32
+                if is_host_amd64_elf; then {
+                    err "x32 linux unsupported"
+                }; else
+                    _cputype=i686
+                fi
+                ;;
+            mips64)
+                _cputype=$(get_endianness mips '' el)
+                ;;
+            powerpc64)
+                _cputype=powerpc
+                ;;
+            aarch64)
+                _cputype=armv7
+                if [ "$_ostype" = "linux-android" ]; then
+                    _ostype=linux-androideabi
+                else
+                    _ostype="${_ostype}eabihf"
+                fi
+                ;;
+            riscv64gc)
+                err "riscv64 with 32-bit userland unsupported"
+                ;;
+        esac
+    fi
+
+    # treat armv7 systems without neon as plain arm
+    if [ "$_ostype" = "unknown-linux-gnueabihf" ] && [ "$_cputype" = armv7 ]; then
+        if ensure grep '^Features' /proc/cpuinfo | grep -q -v neon; then
+            # At least one processor does not have NEON.
+            _cputype=arm
+        fi
+    fi
+
+    _arch="${_cputype}-${_ostype}"
 
     RETVAL="$_arch"
 }
 
 say() {
-    local green=`tput setaf 2 2>/dev/null || echo ''`
-    local reset=`tput sgr0 2>/dev/null || echo ''`
     echo "$1"
 }
 
 err() {
-    local red=`tput setaf 1 2>/dev/null || echo ''`
-    local reset=`tput sgr0 2>/dev/null || echo ''`
+    local red
+    local reset
+    red=$(tput setaf 1 2>/dev/null || echo '')
+    reset=$(tput sgr0 2>/dev/null || echo '')
     say "${red}ERROR${reset}: $1" >&2
     exit 1
-}
-
-has_required_glibc() {
-    local _ldd_version="$(ldd --version 2>&1 | head -n1)"
-    # glibc version string is inconsistent across distributions
-    # instead check if the string does not contain musl (case insensitive)
-    if echo "${_ldd_version}" | grep -iv musl >/dev/null; then
-        local _glibc_version=$(echo "${_ldd_version}" | awk 'NR==1 { print $NF }')
-        local _glibc_major_version=$(echo "${_glibc_version}" | cut -d. -f1)
-        local _glibc_min_version=$(echo "${_glibc_version}" | cut -d. -f2)
-        local _min_major_version=2
-        local _min_minor_version=17
-        if [ "${_glibc_major_version}" -gt "${_min_major_version}" ] \
-            || { [ "${_glibc_major_version}" -eq "${_min_major_version}" ] \
-            && [ "${_glibc_min_version}" -ge "${_min_minor_version}" ]; }; then
-            return 0
-        else
-            say "This operating system needs glibc >= ${_min_major_version}.${_min_minor_version}, but only has ${_libc_version} installed."
-        fi
-    else
-        say "This operating system does not support dynamic linking to glibc."
-    fi
-
-    return 1
 }
 
 need_cmd() {
@@ -247,10 +443,6 @@ check_cmd() {
     return $?
 }
 
-need_ok() {
-    if [ $? != 0 ]; then err "$1"; fi
-}
-
 assert_nz() {
     if [ -z "$1" ]; then err "assert_nz $2"; fi
 }
@@ -259,8 +451,7 @@ assert_nz() {
 # will immediately terminate with an error showing the failing
 # command.
 ensure() {
-    "$@"
-    need_ok "command failed: $*"
+    if ! "$@"; then err "command failed: $*"; fi
 }
 
 # This is just for indicating that commands' results are being
