feat(install-path): teach shell installer to add dirs to PATH

diff --git a/cargo-dist/templates/installer.sh.j2 b/cargo-dist/templates/installer.sh.j2
--- a/cargo-dist/templates/installer.sh.j2
+++ b/cargo-dist/templates/installer.sh.j2
@@ -72,8 +72,8 @@ download_binary_and_run_installer() {
     local _file="$_dir/input$_zip_ext"
 
     say "downloading $APP_NAME $APP_VERSION ${_arch}" 1>&2
-    say "  from $_url" 1>&2
-    say "  to $_file" 1>&2
+    # say "  from $_url" 1>&2
+    # say "  to $_file" 1>&2
 
     ensure mkdir -p "$_dir"
     
@@ -87,7 +87,6 @@ download_binary_and_run_installer() {
     fi
 
     # unpack the archive
-    say "unpacking to $_dir" 1>&2
     case "$_zip_ext" in
         ".zip")
             ensure unzip -q "$_file" -d "$_dir"
@@ -101,10 +100,6 @@ download_binary_and_run_installer() {
             ;;
     esac
 
-    for _bin_name in $_bins; do
-        say "  unpacked $_bin_name"
-    done
-
     install "$_dir" "$_bins" "$@"
     local _retval=$?
 
@@ -113,28 +108,99 @@ download_binary_and_run_installer() {
     return "$_retval"
 }
 
+# See discussion of late-bound vs early-bound for why we use single-quotes with env vars
+# shellcheck disable=SC2016
 install() {
+    # This code needs to both compute certain paths for itself to write to, and
+    # also write them to shell/rc files so that they can look them up to e.g.
+    # add them to PATH. This requires an active distinction between paths
+    # and expressions that can compute them.
+    #
+    # The distinction lies in when we want env-vars to be evaluated. For instance
+    # if we determine that we want to install to $HOME/.myapp, which do we add
+    # to e.g. $HOME/.profile:
+    #
+    # * early-bound: export PATH="/home/myuser/.myapp:$PATH"
+    # * late-bound:  export PATH="$HOME/.myapp:$PATH"
+    #
+    # In this case most people would prefer the late-bound version, but in other
+    # cases the early-bound version might be a better idea. In particular when using
+    # other env-vars than $HOME, they are more likely to be only set temporarily
+    # for the duration of this install script, so it's more advisable to erase their
+    # existence with early-bounding.
+    #
+    # This distinction is handled by "double-quotes" (early) vs 'single-quotes' (late).
+    #
+    # This script has a few different variants, the most complex one being the
+    # CARGO_HOME version which attempts to install things to Cargo's bin dir,
+    # potentially setting up a minimal version if the user hasn't ever installed Cargo.
+    #
+    # In this case we need to:
+    #
+    # * Install to $HOME/.cargo/bin/
+    # * Create a shell script at $HOME/.cargo/env that:
+    #   * Checks if $HOME/.cargo/bin/ is on PATH
+    #   * and if not prepends it to PATH
+    # * Edits $HOME/.profile to run $HOME/.cargo/env (if the line doesn't exist)
+    #
+    # To do this we need these 4 values:
+
+    # The actual path we're going to install to
     local _install_dir
+    # Path to the an shell script that adds install_dir to PATH
+    local _env_script_path
+    # Potentially-late-bound version of install_dir to write env_script
+    local _install_dir_expr
+    # Potentially-late-bound version of env_script_path to write to rcfiles like $HOME/.profile
+    local _env_script_path_expr
+
 {% if install_path.kind == "CargoHome" %}
     # first try CARGO_HOME, then fallback to HOME
     if [ -n "${CARGO_HOME:-}" ]; then
-        _install_dir="$CARGO_HOME/bin/"
+        _install_dir="$CARGO_HOME/bin"
+        _env_script_path="$CARGO_HOME/env"
+        # If CARGO_HOME was set but it ended up being the default $HOME-based path,
+        # then keep things late-bound. Otherwise bake the value for safety.
+        # This is what rustup does, and accurately reproducing it is useful.
+        if [ -n "${HOME:-}" ]; then
+            if [ "$HOME/.cargo/bin" = "$_install_dir" ]; then
+                _install_dir_expr='$HOME/.cargo/bin'
+                _env_script_path_expr='$HOME/.cargo/env'
+            else
+                _install_dir_expr="$_install_dir"
+                _env_script_path_expr="$_env_script_path"
+            fi
+        else
+            _install_dir_expr="$_install_dir"
+            _env_script_path_expr="$_env_script_path"
+        fi
     elif [ -n "${HOME:-}" ]; then
-        _install_dir="$HOME/.cargo/bin/"
+        _install_dir="$HOME/.cargo/bin"
+        _env_script_path="$HOME/.cargo/env"
+        _install_dir_expr='$HOME/.cargo/bin'
+        _env_script_path_expr='$HOME/.cargo/env'
     else
         err "could not find your CARGO_HOME or HOME dir to install binaries to"
     fi
 {% elif install_path.kind == "HomeSubdir" %}
     # Install to this subdir of the user's home dir
+    # In this case we want to be late-bound, as $HOME is reliable/nice.
     if [ -n "${HOME:-}" ]; then
         _install_dir="$HOME/{{ install_path.subdir }}"
+        _env_script_path="$HOME/{{ install_path.subdir }}/env"
+        _install_dir_expr='$HOME/{{ install_path.subdir }}'
+        _env_script_path_expr='$HOME/{{ install_path.subdir }}/env'
     else
         err "could not find your HOME dir to install binaries to"
     fi
 {% elif install_path.kind == "EnvSubdir" %}
-    # Install to this subdir of the user's {{ install_path.env_key }} dir
+    # Install to this subdir of the user's {{ install_path.env_key }} dir.
+    # In this case we want to be early-bound, as the env-var can't be trusted longterm.
     if [ -n "{{ "${" }}{{ install_path.env_key }}:-}" ]; then
         _install_dir="${{ install_path.env_key }}/{{ install_path.subdir }}"
+        _env_script_path="${{ install_path.env_key }}/{{ install_path.subdir }}/env"
+        _install_dir_expr="$_install_dir"
+        _env_script_path_expr="$_env_script_path"
     else
         err "could not find your {{ install_path.env_key }} dir to install binaries to"
     fi
@@ -152,9 +218,71 @@ install() {
         cp "$_bin" "$_install_dir"
         # unzip seems to need this chmod
         chmod +x "$_install_dir/$_bin_name"
+        say "  $_bin_name"
     done
 
     say "everything's installed!"
+
+    add_install_dir_to_path "$_install_dir_expr" "$_env_script_path" "$_env_script_path_expr"
+}
+
+add_install_dir_to_path() {
+    # Edit rcfiles ($HOME/.profile) to add install_dir to $PATH
+    #
+    # We do this slightly indirectly by creating an "env" shell script which checks if install_dir
+    # is on $PATH already, and prepends it if not. The actual line we then add to rcfiles
+    # is to just run that script. This allows us to blast it into lots of different rcfiles and
+    # have it run multiple times without causing problems. It's also specifically compatible
+    # with the system rustup uses, so that we don't conflict with it.
+    local _install_dir_expr="$1"
+    local _env_script_path="$2"
+    local _env_script_path_expr="$3"
+    if [ -n "${HOME:-}" ]; then
+        local _rcfile="$HOME/.profile"
+        local _line_to_add=". \"$_env_script_path_expr\""
+
+        # Check if the line is already in the file
+        # grep: 0 if matched, 1 if no match, and 2 if an error occurred
+        #
+        # Ideally we could use quiet grep (-q), but that makes "match" and "error"
+        # have the same behaviour, when we want "no match" and "error" to be the same
+        # (on error we want to create the file, which >> conveniently does)
+        if ! grep -F "$_line_to_add" "$_rcfile" > /dev/null 2>/dev/null; then 
+            # Ok we definitely want to add the source line, but first write the script
+            # but only if it doesn't already exist, to be safe.
+            if [ ! -f "$_env_script_path" ]; then 
+                write_env_script "$_install_dir_expr" "$_env_script_path"
+            fi
+
+            # If the script now exists, add the line to source it to the rcfile
+            # (This will also create the rcfile if it doesn't exist)
+            if [ -f "$_env_script_path" ]; then 
+                echo "$_line_to_add" >> "$_rcfile"
+                say ""
+                say "To add $_install_dir_expr to your PATH, either restart your shell or run:"
+                say ". \"$_env_script_path_expr\""
+            fi
+        fi
+    fi
+}
+
+write_env_script() {
+    # write this env script to the given path (this cat/EOF stuff is a "heredoc" string)
+    local _install_dir_expr="$1"
+    local _env_script_path="$2"
+    cat <<EOF > "$_env_script_path"
+#!/bin/sh
+# add binaries to PATH if they aren't added yet
+# affix colons on either side of \$PATH to simplify matching
+case ":\${PATH}:" in
+    *:"$_install_dir_expr":*)
+        ;;
+    *)
+        # Prepending path in case a system-installed binary needs to be overridden
+        export PATH="$_install_dir_expr:\$PATH"
+        ;;
+esac
+EOF
 }
 
 check_proc() {
