chore: cleanup error handling in scripts
* propagate failure
* add more wildcard cases
* cleanup messages

diff --git a/cargo-dist/templates/installer/installer.sh.j2 b/cargo-dist/templates/installer/installer.sh.j2
--- a/cargo-dist/templates/installer/installer.sh.j2
+++ b/cargo-dist/templates/installer/installer.sh.j2
@@ -133,7 +133,7 @@ download_binary_and_run_installer() {
 
     # Lookup what archives support this platform
     local _artifact_name
-    _artifact_name="$(select_archive_for_arch "$_true_arch")"
+    _artifact_name="$(select_archive_for_arch "$_true_arch")" || return 1
     local _bins
     local _zip_ext
     local _arch
@@ -169,7 +169,7 @@ download_binary_and_run_installer() {
             {%- endif%}
             ;;{% endfor %}
         *)
-            err "internal installer error: $_artifact_name doesn't exist!?"
+            err "internal installer error: selected download $_artifact_name doesn't exist!?"
             ;;
     esac
 
@@ -182,11 +182,7 @@ download_binary_and_run_installer() {
     # download the archive
     local _url="$ARTIFACT_DOWNLOAD_URL/$_artifact_name"
     local _dir
-    if ! _dir="$(ensure mktemp -d)"; then
-        # Because the previous command ran in a subshell, we must manually
-        # propagate exit status.
-        exit 1
-    fi
+    _dir="$(ensure mktemp -d)" || return 1
     local _file="$_dir/input$_zip_ext"
 
     say "downloading $APP_NAME $APP_VERSION ${_arch}" 1>&2
@@ -274,6 +270,9 @@ json_binary_aliases() {
     "{{ artifact.target_triple }}")
         echo '{{ bin_aliases[artifact.target_triple] | tojson }}'
         ;;{% endfor %}
+    *)
+        echo '{}'
+        ;;
     esac
 }
 
@@ -285,15 +284,17 @@ aliases_for_binary() {
     "{{ artifact.target_triple }}")
         case "$_bin" in
         {%- for source, dests in bin_aliases[artifact.target_triple] | items %}
-            "{{ source }}")
-                echo "{{ dests | join(" ") }}"
-            ;;
-        {%- endfor %}
+        "{{ source }}")
+            echo "{{ dests | join(" ") }}"
+            ;;{% endfor %}
         *)
             echo ""
             ;;
         esac
         ;;{% endfor %}
+    *)
+        echo ""
+        ;;
     esac
 }
 
@@ -316,10 +317,10 @@ select_archive_for_arch() {
             {%- endfor %}
             ;;{% endfor %}
         *)
-            err "there isn't a package for $_true_arch"
+            err "there isn't a download for your platform $_true_arch"
             ;;
     esac
-    err "no compatible archives were found for $_true_arch"
+    err "no compatible downloads were found for your platform $_true_arch"
 }
 
 check_glibc() {
